import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import styled from 'styled-components'
import DynNavbar from '../components/DynNavbar'
import Footer from '../components/Footer'
import bg from '../public/images/home/bg.jpeg'
import NextJsCarousel from '../components/Carousel'


const Hero = styled.div`
  height: 88vh;
  display: flex;
  justify-content: center;
  background-image: url(${bg});
  align-items: center;
  padding-left: 10%;
  padding-right: 10%;
`

const CarouselHero = styled.div`
  height: 88vh;
  display: flex;
  justify-content: center;
  background-image: url(${bg});
  align-items: center;
  padding-top: 2%;
  padding-left: 0%;
  padding-right: 0%;
`

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Qibo Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <Image rel="icon" href="/../public/Q.png" />
      </Head>
      <DynNavbar/>

      <Hero>
      <div className='two-posts'>
        <div className='home-card'>
          <div className='row-padded-element'>          
            <div className='h1-custom'>The open source operating system for quantum hardware</div>
          </div>
          <div className='row-element'>          
            <div className='p-home'>Quantum programming, simulation, control and remote access</div>
          </div>
        </div>
        <div className='home-card'>
          <img src='/images/home/Hero.png' alt='/'/>
        </div>
      </div>
      </Hero>

      <div className='in-container'>
        <div className='row-padded-element'>          
          <div className='h1-custom'>An open quantum ecosystem</div>
        </div>
      </div>
      <div className='in-container'>
        <div className='row-element'>       
          <div className='p-home'>Qibo is an end-to-end open source platform for quantum simulation, 
            quantum hardware control and remote access. It has a comprehensive, 
            flexible ecosystem of tools, libraries and community resources that 
            lets researchers and users to quickly deploy quantum powered 
            applications.
          </div>
        </div>
      </div>

      <div className='in-container'>
        <div className='four-posts'>
            <div className='home-card'>
              <div className='in-container'>
                <img src='/images/home/finances_p.png' alt='/'/>
              </div>
              <div className='h3-custom'> Applications </div>
              <div className='p-home-small'> 
                We provide an open source codebase of pre-coded quantum algorithms 
                for applications in quantum machine learning, chemistry, industry among others.
              </div>
            </div>
            <div className='home-card'>
              <div className='in-container'>
                <img src='/images/home/code_p.png' alt='/'/>
              </div>
              <div className='h3-custom'> Algorithms </div>
              <div className='p-home-small'> 
                We offer tutorials and code examples for quantum algorithms that
                can be quickly modified and adapted by developers.
              </div>
            </div>
            <div className='home-card'>
              <div className='in-container'>
                <img src='/images/home/lab_p.png' alt='/'/>
              </div>
              <div className='h3-custom'> Laboratory tools </div>
              <div className='p-home-small'> 
                We support hardware control procedures for laboratories technologies,
                including pulses sequence generation, job submission and results recontruction.
              </div>
            </div>
            <div className='home-card'>
              <div className='in-container'>
                <img src='/images/home/hw_p.png' alt='/'/>
              </div>
              <div className='h3-custom'> Open hardware </div>
              <div className='p-home-small'> 
                We suggest accessible hardware for quantum simulation and hardware implementation.
              </div>
            </div>
        </div>
      </div>

      <CarouselHero>
        <NextJsCarousel/>
      </CarouselHero>

      <div className='in-container'>
        <div className='row-padded-element'>          
          <div className='h1-custom'>Open Hardware</div>
        </div>
      </div>
      <div className='in-container'>
        <div className='row-element'>       
          <div className='p-home'>
            Quantum simulation is a challenging task which involves the 
            identifications of the classical resources and its limitations.
          </div>
        </div>
      </div>
      <div className='small-container'>
        <div className='row-element'>       
          <img src='/images/home/Hw.png' alt='/'/>
        </div>
      </div>

      <Hero>
        <div className='home-card'>
          <div className='h1-custom'>
            Develop, build and collaborate easily with Qibo!
          </div>
          <div className='p-home'>
            Join Qibo and help us to build an open quantum ecosystem.
          </div>
        </div>
      </Hero>
    
      <Footer/>

    </div>
  )
}




