import dynamic from "next/dynamic";
import DynNavbar from '../components/DynNavbar'
import styled from 'styled-components'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Footer from '../components/Footer'


const Hero = styled.div`
  display: flex;
  padding-bottom: 10px;
  justify-content: center;
  background: #fff;
  align-items: center;
  padding-left: 10%;
  padding-right: 10%;
`

const Notebook = dynamic(() => import("../components/Notebook"), {
  ssr: false
});

const DARK_MODE = true;

export default function mdPage() {
    
  return (
    <div className={styles.container}>
      <Head>
        <title>Qibo Tutorials</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/x-icon" href="/favicon.ico" />
      </Head> 
    <DynNavbar />
    <Hero>
    <div style={{ backgroundColor: "rgba(0, 0, 0, 0)" }}>
      <Notebook
        filePath="/notebooks/parameter_shift_rule.ipynb"
        className="notebook-class"
        notebookInputLanguage="python"
        // notebookOutputLanguage="python"
        inputCodeDarkTheme={DARK_MODE}
        outputDarkTheme={DARK_MODE}
        inputMarkdownDarkTheme={DARK_MODE}
        showInputLineNumbers={true}
        showOutputLineNumbers={false}
        outputTextClassName="output-text"
        inputTextClassName="input-text"
        outputBlockClassName="output-block"
        outputImageClassName="output-image"
        outputOuterClassName="output-outer"
        inputOuterClassName="input-outer"
        outputBorderClassName="output-border"
        inputBorderClassName="input-border"
        outputTableClassName="output-table"
        withOnClick={true}
        inputMarkdownBlockClassName="input-markdown-block"
        inputCodeBlockClassName="input-code-block"
        hideCodeBlocks={false}
        hideMarkdownBlocks={false}
        hideAllOutputs={false}
        hideAllInputs={false}
        remarkPlugins={[]}
        rehypePlugins={[]}
      />
    </div>
    </Hero>

    </div>
  );
}
