import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'
import styled from 'styled-components'

const Hero = styled.div`
  height: 88vh;
  display: flex;
  justify-content: center;
  background: #fff;
  align-items: center;
`

const Heading = styled.div`
  color: #883b8f;
  font-size: 60px;
  font-weight: 800;
`

export default function About() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Qibo papers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
      <Hero>
        <Heading>
          Cite us!
        </Heading>
      </Hero>
    </div>
  )
}