import Head from 'next/head'
import styles from '../styles/Home.module.css'
import styled from 'styled-components'
import fs from 'fs'
import path from 'path'
import matter from 'gray-matter'
import Tutorial from '../components/Tutorial'
import DynNavbar from '../components/DynNavbar'
import Footer from '../components/Footer'


const Hero = styled.div`
  display: flex;
  padding-bottom: 10px;
  justify-content: center;
  background: #fff;
  align-items: center;
  padding-left: 10%;
  padding-right: 10%;
  background-image: url("/images/backgrounds/circuits.svg");
  background-size: cover;
  background-position: center center;
  background-repeat: no-repeat;
  background-attachment: fixed;
`


export default function Tutorials({tutorials}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Qibo Tutorials</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/x-icon" href="/favicon.ico" />
      </Head> 
      <DynNavbar/>
       <Hero>
        <div className='posts'>
          {tutorials.map((tutorial, index) => (
            <Tutorial tutorial={tutorial} />
          ))}
        </div>
      </Hero>
      <Footer/>
    </div>
  )
}


export async function getStaticProps() {
  // get files from the posts directory
  const files = fs.readdirSync(path.join('tutorials'))
  // get slug and frontmatter
  const tutorials = files.map(filename => {
    // create the slug
    const slug = filename.replace('.mdx', '')
    const markdownWithMeta = fs.readFileSync(path.join('tutorials', filename), 'utf-8')

    const {data:frontmatter} = matter(markdownWithMeta)

    return{
      slug,
      frontmatter
    }
  })
  return {
    props: {
      tutorials
    }
  }
}