import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import styled from 'styled-components'
import fs from 'fs'
import path from 'path'
import matter from 'gray-matter'
import Post from '../components/Post'
import DynNavbar from '../components/DynNavbar'
import Footer from '../components/Footer'


const Hero = styled.div`
  height: 88vh;
  display: flex;
  padding-bottom: 10px;
  justify-content: center;
  background: #fff;
  align-items: center;
  padding-left: 10%;
  padding-right: 10%;
`


export default function Tutorials({posts}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Qibo Tutorials</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
      <DynNavbar/>
       <Hero>
        <div className='posts'>
          {posts.map((post, index) => (
            <Post post={post} />
          ))}
        </div>
      </Hero>
      <Footer/>
    </div>
  )
}


export async function getStaticProps() {
  // get files from the posts directory
  const files = fs.readdirSync(path.join('posts'))
  // get slug and frontmatter
  const posts = files.map(filename => {
    // create the slug
    const slug = filename.replace('.md', '')
    const markdownWithMeta = fs.readFileSync(path.join('posts', filename), 'utf-8')

    const {data:frontmatter} = matter(markdownWithMeta)

    return{
      slug,
      frontmatter
    }
  })
  return {
    props: {
      posts
    }
  }
}