name: Deploy Next.js site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main", "edo"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          submodules: True
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn
      - name: Setup Pages
        uses: actions/configure-pages@v2
        with:
          # Automatically inject basePath in your Next.js configuration file and disable
          # server side image optimization (https://nextjs.org/docs/api-reference/next/image#unoptimized).
          #
          # You may remove this line if you want to manage the configuration yourself.
          static_site_generator: next
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            .next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-
      - run: ls -a public/packages #TODO delete
      - name: Clone qibo repository
        uses: actions/checkout@v2
        with:
          repository: qiboteam/qibo
          clean: False
          path: public/packages/qibo

      - name: Deploy qibo documentation
        run: |
          python -m pip install --upgrade pip
          ls -a public/packages #TODO: remove
          ls -a public/packages/qibo #TODO: remove
          ls -a public/packages/qibocal  #TODO: remove
          ls -a public/packages/qibocal/serverscripts/web/  #TODO: remove
          cd public/packages/qibo
          pip install .[docs]
          sudo apt install pandoc
          cd doc
          make html
      - name: Clone qibocal repository
        uses: actions/checkout@v2
        with:
          repository: qiboteam/qibocal
          clean: False
          path: public/packages/qibocal
      - name: Deploy qibocal documentation
        run: |
          rm public/packages/qibocal/src/qibocal/web/static/styles.css # TODO: change file in a PR
          ln -s public/packages/qibocal/src/qibocal/web/static/styles.css styles.css # TODO: change file in a PR
          ln -s public/packages/qibocal/src/qibocal/web/static/styles.css styles.css # TODO: change file in a PR
          ls styles #TODO: remove
          cd public/packages/qibocal
          pip install .[docs]
          cd doc
          make html
      - name: Install dependencies
        run: yarn install
      - name: Build with Next.js
        run: yarn build
      - name: Static HTML export with Next.js
        run: yarn next export
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./out
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
